input {
  file {
    path => "./cowrie/logs/cowrie.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "cowrie-logs"
  }
  stdout { codec => rubydebug }
}